config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "application#redirect_root"

  namespace :admin do
    resources :residences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/residence.rb
class Residence < ApplicationRecord
  belongs_to :residence_status
  has_and_belongs_to_many :residence_features

  enum finality: [:sale, :rent, :sale_rent]
  enum capture_type: [:gold, :silver, :promotional]

  def features
    residence_features
  end

  def self.finalities_options
    finalities.map do |finality, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.finalities.#{finality}"), finality]
    end
  end

  def self.capture_types_options
    capture_types.map do |capture_type, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.capture_types.#{capture_type}"), capture_type]
    end
  end
end

app/models/residence_feature.rb
class ResidenceFeature < ActiveRecord::Base
  has_and_belongs_to_many :residences
end

app/models/residence_status.rb
class ResidenceStatus < ActiveRecord::Base
  has_many :residences
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
  

app/controllers/admin/residences_controller.rb
class Admin::ResidencesController < AdminController
  before_action :set_residence, only: [:show, :edit, :update, :destroy]
  before_action :convert_moneys, only: [:create, :update]
  before_action :convert_dates, only: [:create, :update]

  # GET /residences
  # GET /residences.json
  def index
    @residences = Residence.all
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
  end

  # GET /residences/new
  def new
    @residence = Residence.new
    set_options
  end

  # GET /residences/1/edit
  def edit
    set_options
    disconvert_dates @residence
  end

  # POST /residences
  # POST /residences.json
  def create
    set_options
    @residence = Residence.new(residence_params)

    respond_to do |format|
      if @residence.save
        format.html { redirect_to [:admin, @residence], notice: 'Residence was successfully created.' }
        format.json { render :show, status: :created, location: @residence }
      else
        format.html { render :new }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residences/1
  # PATCH/PUT /residences/1.json
  def update
    respond_to do |format|
      if @residence.update(residence_params)
        format.html { redirect_to [:admin, @residence], notice: 'Residence was successfully updated.' }
        format.json { render :show, status: :ok, location: @residence }
      else
        format.html { render :edit }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence.destroy
    respond_to do |format|
      format.html { redirect_to admin_residences_url, notice: 'Residence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residence
      @residence = Residence.find(params[:id])
    end

    def convert_moneys
      moneys = %i[
        market_price
        sale_price
        condo_price
        iptu_price
        rent_price
      ]

      moneys.each do |money|
        converted = params[:residence][money] 
        converted = converted.gsub!(".", "")
        converted = converted.gsub!(",", ".")
        converted = converted.to_f
        params[:residence][money] = converted
      end
    end

    def convert_dates
      date_fields.each do |date|
        converted = params[:residence][date] 
        unless converted.blank?
          converted = Date.strptime(converted, '%d/%m/%Y')
          params[:residence][date] = converted
        end
      end
    end

    def disconvert_dates(residence)
      date_fields.each do |date|
        converted = residence[date]
        unless converted.blank?
          converted = converted.strftime("%d/%m/%Y")
        end
        residence[date] = converted
      end
    end

    def date_fields
      %i[
        suspention_date
        construction_date
        reform_date
      ]
    end

    def residence_params
      params.require(:residence).permit(
        :condo_name, :address, :number, :complement, 
        :neighborhood, :city, :state, :postal_code, 
        :bedroom, :suite, :bathroom, :living_room, 
        :covered_parking, :not_covered_parking, 
        :total_parking_lot, :payed_property, :building_aera, 
        :total_area, :accept_exchange, :exchange, :payed_condo, 
        :realstate_county_subscription, :residence_registration_number,
        :market_price, :sale_price, :condo_price,
        :iptu_price, :rent_price, :which_floor, :tower,
        :description, :tour_virtual_link, :marketing_authorization, 
        :indicated, :suspention_date, :idealize_commercialization, 
        :media_fee, :construction_date, :reform_date, 
        :how_many_times_can_be_acquired, :how_many_times_acquired,
        :residence_status_id, :finality, :capture_type,
        residence_feature_ids: []
      )
    end

    def set_options
      @residence_statuses = ResidenceStatus.all
      @finalities = Residence.finalities_options
      @capture_types = Residence.capture_types_options
      @features = ResidenceFeature.all.collect { |cat| [cat.value, cat.id] }
      @selected_features = @residence&.features&.present? ? @residence.features.map(&:id) : []
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def redirect_root
    redirect_to admin_residences_url
  end

  protected
  def after_sign_in_path_for(resource)
    admin_residences_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/admin/residences/_form.html.erb
<%= form_with(model: [:admin, residence], local: true) do |form| %>
  <% if residence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(residence.errors.count, "error") %> prohibited this residence from being saved:</h2>

      <ul>
      <% residence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12 m7 no-padding">
      <h5 class="col s12"><%= t ".address" %></h5>

      <div class="input-field col s12 m9">
        <%= form.label :address %>
        <%= form.text_field :address %>
      </div>

      <div class="input-field col s12 m3">
        <%= form.label :number %>
        <%= form.text_field :number %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :complement %>
        <%= form.text_field :complement %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :neighborhood %>
        <%= form.text_field :neighborhood %>
      </div>

      <div class="input-field col s12 m10">
        <%= form.label :city %>
        <%= form.text_field :city %>
      </div>

      <div class="input-field col s12 m2">
        <%= form.label :state %>
        <%= form.text_field :state %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :postal_code %>
        <%= form.text_field :postal_code %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :condo_name %>
        <%= form.text_field :condo_name %>
      </div>

      <h5 class="col s12"><%= t ".features" %></h5>

      <div class="input-field col s12 m12">
        <%= form.select :residence_feature_ids, @features, {}, { multiple: true, selected: @selected_features } %>
        <%= form.label :residence_features %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :bedroom %>
        <%= form.number_field :bedroom %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :suite %>
        <%= form.number_field :suite %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :bathroom %>
        <%= form.number_field :bathroom %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :living_room %>
        <%= form.number_field :living_room %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :covered_parking_lot %>
        <%= form.number_field :covered_parking_lot %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :uncovered_parking_lot %>
        <%= form.number_field :uncovered_parking_lot%>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :total_parking_lot %>
        <%= form.number_field :total_parking_lot, disabled: "", placeholder: "" %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :building_aera %>
        <%= form.number_field :building_aera %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :total_area %>
        <%= form.number_field :total_area %>
      </div>

      <h5 class="col s12"><%= t ".financial" %></h5>

      <div class="input-field col s12 m6">
        <%= form.label :exchange %>
        <%= form.text_field :exchange %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :market_price %>
        <%= form.text_field :market_price, class: "money" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :sale_price %>
        <%= form.text_field :sale_price, class: "money" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :condo_price %>
        <%= form.text_field :condo_price, class: "money" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :iptu_price %>
        <%= form.text_field :iptu_price, class: "money" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :rent_price %>
        <%= form.text_field :rent_price, class: "money" %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :media_fee %>
        <%= form.text_field :media_fee %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :comission_fee %>
        <%= form.text_field :comission_fee %>
      </div>

      <h5 class="col s12"><%= t ".registers" %></h5>

      <div class="col s12 m4">
        <label for="residence_payed_property">
          <%= form.check_box :payed_property %>
          <span><%= t ".payed_property" %></span>
        </label>
      </div>

      <div class="col s12 m4">
        <label for="residence_accept_exchange">
          <%= form.check_box :accept_exchange %>
          <span><%= t ".accept_exchange" %></span>
        </label>
      </div>

      <div class="col s12 m4">
        <label for="residence_payed_condo">
          <%= form.check_box :payed_condo %>
          <span><%= t ".payed_condo" %></span>
        </label>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :realstate_county_subscription %>
        <%= form.text_field :realstate_county_subscription %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :residence_registration_number %>
        <%= form.text_field :residence_registration_number %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :which_floor %>
        <%= form.number_field :which_floor %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :tower %>
        <%= form.text_field :tower %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :suspention_date %>
        <%= form.text_field :suspention_date, class: "datepicker" %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :construction_date %>
        <%= form.text_field :construction_date, class: "datepicker" %>
      </div>

      <div class="input-field col s12 m4">
        <%= form.label :reform_date %>
        <%= form.text_field :reform_date, class: "datepicker" %>
      </div>

      <h5 class="col s12"><%= t ".marketing" %></h5>

      <div class="input-field col s12 m12">
        <%= form.label :description %>
        <%= form.text_area :description, class: "materialize-textarea"%>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :tour_virtual_link %>
        <%= form.text_field :tour_virtual_link %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :marketing_authorization %>
        <%= form.text_field :marketing_authorization %>
      </div>

      <h5 class="col s12"><%= t ".aquisition" %></h5>

      <div class="input-field col s12 m6">
        <%= collection_select(:residence, :residence_status_id, @residence_statuses, :id, :value, {}, { prompt: "Selecione o status", required: true })  %>
        <%= form.label :residence_status %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.select :finality, @finalities, prompt: "Selecione a finalidade" %>
        <%= form.label :finality %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :aquiring %>
        <%= form.number_field :aquiring %>
      </div>

      <div class="input-field col s12 m6">
        <%= form.label :acquired %>
        <%= form.number_field :acquired %>
      </div>

      <div class="input-field col s12 m12">
        <%= form.select :capture_type, @capture_types, prompt: "Selecione o tipo de captação" %>
        <%= form.label :capture_type %>
      </div>

      <!--<div class="input-field col s12 m12">
        <label for="residence_payed_property">
          <input type="checkbox" class="filled-in" value="1" name="residence[idealize_commercialization]" id="residence_payed_property">
          <span>Idealize Commercialization</span>
        </label>
      </div>-->
    </div>
  </div>

  <div class="row">
    <div class="col s12 m6">
      <%= form.submit 'Salvar', class: "waves-effect waves-light text-lighten-1 btn" %>
    </div>
  </div>
<% end %>

app/views/admin/residences/edit.html.erb
<div class="row">
  <div class="col s12 m6">
    <h1><%= t ".edit_residence" %></h1>
  </div>
</div>

<%= render 'form', residence: @residence %>

<div class="row">
  <div class="col s12 m6">
    <%= link_to t(".show"), [:admin, @residence] %> |
    <%= link_to t(".back"), admin_residences_path %>
  </div>
</div>

app/views/admin/residences/index.html.erb
<h1><%= t ".residences" %></h1>

<table>
  <thead>
    <tr>
      <th><%= t ".id" %></th>
      <th><%= t ".address" %></th>
      <th><%= t ".house_number" %></th>
      <th><%= t ".neighborhood" %></th>
      <th><%= t ".city" %></th>
      <th><%= t ".state" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residences.each do |residence| %>
      <tr>
        <td><%= residence.id %></td>
        <td><%= residence.address %></td>
        <td><%= residence.number %></td>
        <td><%= residence.neighborhood %></td>
        <td><%= residence.city %></td>
        <td><%= residence.state %></td>
        <td><%= link_to t(".show"), [:admin, residence] %></td>
        <td><%= link_to t(".edit"), edit_admin_residence_path(residence) %></td>
        <td><%= link_to t(".delete"), [:admin, residence], method: :delete, data: { confirm: "Você tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(".new_residence"), new_admin_residence_path, class: "waves-effect waves-light text-lighten-1 btn" %>

app/views/admin/residences/new.html.erb
<div class="row">
  <div class="col s12 m6">
    <h1><%= t ".new_residence" %></h1>
  </div>
</div>

<%= render "form", residence: @residence %>

<div class="row">
  <div class="col s12 m6">
    <%= link_to t(".back"), admin_residences_path %>
  </div>
</div>

app/views/admin/residences/show.html.erb
<p>
  <strong>Condo name:</strong>
  <%= @residence.condo_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @residence.address %>
</p>

<p>
  <strong>Number:</strong>
  <%= @residence.number %>
</p>

<p>
  <strong>Complement:</strong>
  <%= @residence.complement %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @residence.neighborhood %>
</p>

<p>
  <strong>City:</strong>
  <%= @residence.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @residence.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @residence.postal_code %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @residence.bedroom %>
</p>

<p>
  <strong>Suite:</strong>
  <%= @residence.suite %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @residence.bathroom %>
</p>

<p>
  <strong>Living room:</strong>
  <%= @residence.living_room %>
</p>

<p>
  <strong>Covered parking:</strong>
  <%= @residence.covered_parking_lot %>
</p>

<p>
  <strong>Not covered parking:</strong>
  <%= @residence.uncovered_parking_lot %>
</p>

<p>
  <strong>Total parking:</strong>
  <%= @residence.total_parking_lot %>
</p>

<p>
  <strong>Payed property:</strong>
  <%= @residence.payed_property %>
</p>

<p>
  <strong>Building aera:</strong>
  <%= @residence.building_aera %>
</p>

<p>
  <strong>Total area:</strong>
  <%= @residence.total_area %>
</p>

<p>
  <strong>Accept exchange:</strong>
  <%= @residence.accept_exchange %>
</p>

<p>
  <strong>Exchange:</strong>
  <%= @residence.exchange %>
</p>

<p>
  <strong>Payed condo:</strong>
  <%= @residence.payed_condo %>
</p>

<p>
  <strong>Realstate county subscription:</strong>
  <%= @residence.realstate_county_subscription %>
</p>

<p>
  <strong>Residence registration number:</strong>
  <%= @residence.residence_registration_number %>
</p>

<p>
  <strong>Market price:</strong>
  <%= @residence.market_price %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @residence.sale_price %>
</p>

<p>
  <strong>Condo price:</strong>
  <%= @residence.condo_price %>
</p>

<p>
  <strong>Iptu price:</strong>
  <%= @residence.iptu_price %>
</p>

<p>
  <strong>Rent price:</strong>
  <%= @residence.rent_price %>
</p>

<p>
  <strong>Which floor:</strong>
  <%= @residence.which_floor %>
</p>

<p>
  <strong>Tower:</strong>
  <%= @residence.tower %>
</p>

<p>
  <strong>Description:</strong>
  <%= @residence.description %>
</p>

<p>
  <strong>Tour virtual link:</strong>
  <%= @residence.tour_virtual_link %>
</p>

<p>
  <strong>Keys local:</strong>
  <%= @residence.tour_virtual_link %>
</p>

<p>
  <strong>Marketing authorization:</strong>
  <%= @residence.marketing_authorization %>
</p>

<p>
  <strong>Suspention date:</strong>
  <%= @residence.suspention_date %>
</p>

<p>
  <strong>Idealize commercialization:</strong>
  <%= @residence.idealize_commercialization %>
</p>

<p>
  <strong>Media fee:</strong>
  <%= @residence.media_fee %>
</p>

<p>
  <strong>Comission fee:</strong>
  <%= @residence.comission_fee %>
</p>

<p>
  <strong>Construction date:</strong>
  <%= @residence.construction_date %>
</p>

<p>
  <strong>Reform date:</strong>
  <%= @residence.reform_date %>
</p>

<p>
  <strong>How many times can be acquired:</strong>
  <%= @residence.aquiring %>
</p>

<p>
  <strong>How many times acquired:</strong>
  <%= @residence.acquired %>
</p>

<%= link_to 'Editar', edit_admin_residence_path(@residence) %> |
<%= link_to 'Voltar', admin_residences_path %>

app/views/home/index.html.erb
<h1><%= t "hello" %></h1>
<label>
  <input type="checkbox" checked="checked"/>
</label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Niemeyer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper teal">
        <div class="container">
          <%= link_to 'Idealize', root_path, class: 'brand-logo' %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li>
              <%= link_to t(".logout"), destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
              <%= link_to t(".login"), new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% if !flash.empty? %>
        <% flash.keys.each do |k| %>
          <div class="row">
            <div class="col s12 m6 offset-m3 no-padding">
              <div class="card red darken-1">
                <div class="card-content white-text">
                  <p><%= flash[k] %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>